version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    container_name: mysqlcontainer
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: 121212

  eurekaserver:
    image: cmeher196/eurekaserver
    restart: always
    container_name: eurekaservercontainer
    network_mode: host
    ports:
      - 8761:8761
   
  userauthservice:
    image: cmeher196/livescoreuserservice:eureka
    restart: always
    container_name: userauthservicecontainer
    network_mode: host
    ports:
      - 8082:8082
    depends_on:
      - eurekaserver
      - mysql

 
  mongo:
    image: mongo
    container_name: mongocontainer
    ports:
      - 27017:27017
    environment:
      MONGO_URL: mongodb://localhost:27017/favouriteDB
    network_mode: host

      
  favouriteservice:
    image: cmeher196/livescorefavservice:eureka
    restart: always
    container_name: favouriteservicecontainer
    network_mode: host
    ports:
      - 8081:8081
    # environment:
    #   MONGO_URL: mongodb://mongo/favouriteDB
    depends_on:
      - eurekaserver
      - mongo
     
  livescoreruiapp:
    image: cmeher196/livescorereactapp
    restart: always
    ports:
      - 3000:3000
